# Generated by Django 2.0.5 on 2019-10-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='sdividend_yield_sort',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='spb_sort',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='spe_sort',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='synthetical_sort',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
